export const groupon_custom_fields = [
	{
		value:'base_attributes',
		label:'基本属性',
		children:[
			{
				label:'拼团单主题',
				value:'display_name',
			},
			{
				label:'拼团名称',
				value:'shopping_group_name',
			},
			{
				label:'开团时间',
				value:'create_time',
			},
			{
				label:'截单时间',
				value:'orderable_deadline'
			},
			{
				label:'配送日期',
				value:'delivery_date',
			},
			{
				label:'配送时间',
				value:'delivery_time_period',
			},
			{
				label:'点击次数',
				value:'click_count',
			},
			{
				label:'下单数',
				value:'order_placed_count',
			},
			{
				label:'下单人数',
				value:'order_placed_users_count',
			},
			{
				label:'总金额',
				value:'orders_total_settlement_fee',
			},
			{
				label:'商品',
				value:'group_products',
			},
			{
				label:'开团店铺名称',
				value:'initiator_name',
			},
			{
				label:'开团店铺编号',
				value:'initiator_code',
			},
			{
				label:'开团店铺主姓名',
				value:'initiator_keeper_name',
			},
			{
				label:'开团店铺主手机号',
				value:'initiator_keeper_mobile',
			},
			{
				label:'自提店铺名称',
				value:'pick_shop_name',
			},
			{
				label:'状态',
				value:'state_desc',
			},
			{
				label: "销售贡献额度",
				value: 'sales_amount',
				type: 'numCompare'
			}
		]
	},
];
