export const secondRoutes = [
	'integralRules',
	'tagManage',
	'userDetails',
	'shopDetails',
	'goodDetails',
	'releaseGoods',
	'inStock',
	'outStock',
	'inStockNew',
	'outStockNew',
	'inStockDetail',
	'outStockDetail',
	'orderDetail',
	'newCoupon',
	'newCouponShop',
	'userStore',
	'storeRecord',
	'message',
	'sendOutRecord',
	'balanceDetails',
	'overview',
	'incomeDetails',
	'withdrawDetails',
	'withdrawApplication',
	'customWeChatMessage',
	'editWeChatMessage',
	'cashbackSetting',
	'setUserMessage',
	'setting',
	'setMarketingMessage',
	'warningSetting',
	'logs'
];


export const firstRoutes = ['finance', 'home'];
