export const shop_values = [
	{
		value:'base_attributes',
		label:'基本属性',
		children:[
			{
				label:'店铺名称',
				value:'name',
				type:'equal'
			},
			{
				label:'店铺编号',
				value:'code',
				type:'equal'
			},
			{
				label:'商户主姓名',
				value:'keeper_name',
				type:'equal'
			},
			{
				label:'商户主身份证号码',
				value:'keeper_id_card_no',
				type:'equal'
			},
			{
				label:'商户主手机',
				value:'keeper_mobile',
				type:'equal'
			},
			{
				label:'省',
				value:'province_code',
				type:'genderCompare'
			},
			{
				label:'市',
				value:'city_code',
				type:'cityCompare'
			},
			{
				label:'区',
				value:'area_code',
				type:'cityCompare'
			},
			{
				label:'开业时间',
				value:'created_at',
				type:'timeCompare'
			},
			{
				label:'介绍人编号',
				value:'introducer_code',
				type:'equal'
			},
			{
				label:'介绍人姓名',
				value:'introducer_name',
				type:'equal'
			},
			{
				label:'他介绍的店铺数量',
				value:'introduced_shops_count',
				type:'numCompare'
			}
		]
	},
	{
		value:'account_data',
		label:'账户数据',
		children:[
			{
				label:'余额',
				value:'balance',
				type:'numCompare'
			},
			{
				label:'充值总额',
				value:'total_recharge',
				type:'numCompare'
				
			},
			{
				label:'提现总额',
				value:'total_withdrawal',
				type:'timeCompare'
			},
			{
				label:'返现总额',
				value:'total_cashback',
				type:'numCompare'
				
			},
			{
				label:'自提返现总额',
				value:'total_self_pick_cashback',
				type:'numCompare'
			},
			{
				label:'自提佣金总额',
				value:'total_self_pick_commission',
				type:'numCompare'
			},
			{
				label:'自提补贴总额',
				value:'total_self_pick_allowance',
				type:'numCompare'
			},
			{
				label:'销售返现总额',
				value:'total_sale_cashback',
				type:'numCompare'
			},
			{
				label:'销售佣金总额',
				value:'total_sale_commission',
				type:'numCompare'
			},
			{
				label:'销售补贴总额',
				value:'total_sale_allowance',
				type:'numCompare'
			},{
				label:'本月返现',
				value:'month_cashback',
				type:'numCompare'
			},
			{
				label:'本月自提返现',
				value:'current_month_self_pick_cashback',
				type:'numCompare'
			},
			{
				label:'本月自提佣金',
				value:'current_month_self_pick_commission',
				type:'numCompare'
			},
			{
				label:'本月自提补贴',
				value:'current_month_self_pick_allowance',
				type:'numCompare'
			},
			{
				label:'本月销售返现',
				value:'current_month_sale_cashback',
				type:'numCompare'
			},
			{
				label:'本月销售佣金',
				value:'current_month_sale_commission',
				type:'numCompare'
			},
			{
				label:'本月销售补贴',
				value:'current_month_sale_allowance',
				type:'numCompare'
			},
		]
	},
	{
		value:'shop_attributes',
		label:'店铺属性',
		children:[
			{
				label:'状态',
				value:'status',
				type:'equal'
			},
			{
				label:'渠道',
				value:'channel',
				type:'channel'
			},
			{
				label:'商户组',
				value:'groups',
				type:'group'
			},
		]
	},
	{
		value:'distribution_data',
		label:'数据',
		children:[
			{
				label:'分享次数',
				value:'total_sharing',
				type:'numCompare'
			},
			{
				label:'被点击总次数',
				value:'total_click',
				type:'numCompare'
			},
			{
				label:'被点击总人数',
				value:'total_click_users',
				type:'numCompare'
			},
			{
				label:'本月被点击次数',
				value:'current_month_click',
				type:'numCompare'
			},
			{
				label:'本月被点击人数',
				value:'current_month_click_users',
				type:'numCompare'
			}
		]
	},
	{
		value:'sell_data',
		label:'销售数据',
		children:[
			{
				label:'扫码付总额',
				value:'total_code_scan_amount',
				type:'numCompare'
			},
			{
				label:'支付宝总额',
				value:'total_code_scan_alipay',
				type:'numCompare'
				
			},
			{
				label:'微信支付总额',
				value:'total_code_scan_wx',
				type:'timeCompare'
			},
			{
				label:'余额支付总额',
				value:'total_code_scan_balance',
				type:'numCompare'
				
			},
			{
				label:'招行一网通支付总额',
				value:'total_code_scan_cmb',
				type:'numCompare'
			},
			{
				label:'本月扫码付金额',
				value:'current_month_code_scan_amount',
				type:'numCompare'
			},
			{
				label:'本月支付宝支付',
				value:'current_month_code_scan_alipay',
				type:'numCompare'
			},
			{
				label:'本月微信支付',
				value:'current_month_code_scan_wx',
				type:'numCompare'
			},
			{
				label:'本月余额支付',
				value:'current_month_code_scan_balance',
				type:'numCompare'
			},
			{
				label:'本月招行一网通',
				value:'current_month_code_scan_cmb',
				type:'numCompare'
			},{
				label:'订货总额',
				value:'total_order_product_amount',
				type:'numCompare'
			},
			{
				label:'本月订货额',
				value:'current_month_order_product_amount',
				type:'numCompare'
			},
			{
				label:'扫码付订单总数',
				value:'total_code_scan_orders_count',
				type:'numCompare'
			},
			{
				label:'本月扫码付订单数',
				value:'current_month_code_scan_orders_count',
				type:'numCompare'
			}
		]
	},
	{
		value:'self_pick_data',
		label:'自提数据',
		children:[
			{
				label:'预订单总订单数',
				value:'total_self_pick_orders_count',
				type:'numCompare'
			},
			{
				label:'本月预订单订单数',
				value:'current_month_self_pick_orders_count',
				type:'numCompare'
				
			},
			{
				label:'预订单总人数',
				value:'total_self_pick_users_count',
				type:'timeCompare'
			},
			{
				label:'本月预订单人数',
				value:'current_month_self_pick_users_count',
				type:'numCompare'
				
			},
			{
				label:'预订单总额',
				value:'total_self_pick_amount',
				type:'numCompare'
			},
			{
				label:'本月预订单金额',
				value:'current_month_self_pick_amount',
				type:'numCompare'
			}
		]
	},
];


export const operation = {
	'equal':[
		{
			label:'等于',
			value:'=',
			type:'input'
		},
	],
	'timeCompare':[
		{
			label:'等于',
			value:'=',
			type:'timestamp'
		},
		{
			label:'不等于',
			value:'<>',
			type:'timestamp'
		},
		{
			label:'晚于',
			value:'>',
			type:'timestamp'
		},
		{
			label:'晚于(含)',
			value:'>=',
			type:'timestamp'
		},
		{
			label:'早于',
			value:'<',
			type:'timestamp'
		},
		{
			label:'早于(含)',
			value:'<=',
			type:'timestamp'
		},
		{
			label:'区间',
			value:'between',
			type:'period'
		}
	],
	'numCompare':[
		{
			label:'等于',
			value:'=',
			type:'input'
		},
		{
			label:'不等于',
			value:'<>',
			type:'input'
		},
		{
			label:'小于',
			value:'<',
			type:'input'
		},
		{
			label:'小于等于',
			value:'<=',
			type:'input'
		},
		{
			label:'大于',
			value:'>',
			type:'input'
		},
		{
			label:'大于等于',
			value:'>=',
			type:'input'
		},
		{
			label:'区间',
			value:'between',
			type:'inputRange'
		}
	],
	'channel':[
		{
			label:'等于',
			value:'=',
			type:'selectedChannelOneBox'
		},
		{
			label:'等于其中之一',
			value:'in',
			type:'selectedChannelBox'
		},
		{
			label:'不等于以下任意',
			value:'not in',
			type:'selectedChannelBox'
		},
	],
	'group':[
		{
			label:'在以下任意群组中',
			value:'in',
			type:'selectedGroupBox'
		},
		{
			label:'在以下所有群组中',
			value:'all',
			type:'selectedGroupBox'
		},
		{
			label:'不在以下任意群组中',
			value:'not in',
			type:'selectedGroupBox'
		},
		{
			label:'为空',
			value:'is null',
			type:''
		},
		{
			label:'不为空',
			value:'is not null',
			type:''
		},
	],
	'equalCompare':[
		{
			label:'等于',
			value:'=',
			type:'selectedOneBox'
		},
		{
			label:'等于其中之一',
			value:'in',
			type:'selectedBox'
		},
		{
			label:'不等于以下任意',
			value:'not in',
			type:'selectedBox'
		},
	],
	// 'emptyCompare':[
	// 	{
	// 		label:'等于',
	// 		value:'=',
	// 		type:'input'
	// 	},
	// 	{
	// 		label:'为空',
	// 		value:'is null',
	// 		type:''
	// 	},
	// 	{
	// 		label:'不为空',
	// 		value:'is not null',
	// 		type:''
	// 	},
	// ],
	'cityCompare':[
		{
			label:'等于',
			value:'=',
			type:'cityOneBox'
		},
		{
			label:'等于其中之一',
			value:'in',
			type:'cityBox'
		},
		{
			label:'不等于其中任意',
			value:'not in',
			type:'cityBox'
		},
	],
};
